// calculator-vue/calculator-vue/src/App.vue
import { 'App' } from 'vue'
<template>
  <div class="age-calculator">
    <h1>Age Calculator</h1>
    <form @submit.prevent="calculateAge">
      <label>
        Birthdate:
        <input type="date" v-model="birthdate" />
      </label>
      <button type="submit">Calculate Age</button>
    </form>
    <div v-if="age">
      <p>Your age is {{ age.years }} years, {{ age.months }} months, {{ age.days }} days, {{ age.hours }} hours, {{ age.minutes }} minutes, and {{ age.seconds }} seconds old.</p>
    </div>
  </div>
</template>

<script>
export default {
  data() {
    return {
      birthdate: '',
      age: null,
    };
  },
  methods: {
    calculateAge() {
      const birthDate = new Date(this.birthdate);
      const today = new Date();
      let ageYears = today.getFullYear() - birthDate.getFullYear();
      let ageMonths = today.getMonth() - birthDate.getMonth();
      let ageDays = today.getDate() - birthDate.getDate();
      let ageHours = today.getHours() - birthDate.getHours();
      let ageMinutes = today.getMinutes() - birthDate.getMinutes();
      let ageSeconds = today.getSeconds() - birthDate.getSeconds();

      if (ageMonths < 0 || (ageMonths === 0 && ageDays < 0)) {
        ageYears--;
        ageMonths += 12;
        ageDays = (today.getDate() + this.daysInMonth(today.getMonth(), today.getFullYear())) - birthDate.getDate();
      }

      if (ageDays < 0) {
        ageMonths--;
        ageDays += this.daysInMonth(today.getMonth() - 1, today.getFullYear());
      }

      if (ageHours < 0) {
        ageDays--;
        ageHours += 24;
      }

      if (ageMinutes < 0) {
        ageHours--;
        ageMinutes += 60;
      }

      if (ageSeconds < 0) {
        ageMinutes--;
        ageSeconds += 60;
      }

      this.age = {
        years: ageYears,
        months: ageMonths,
        days: ageDays,
        hours: ageHours,
        minutes: ageMinutes,
        seconds: ageSeconds,
      };
    },
    daysInMonth(month, year) {
      return new Date(year, month + 1, 0).getDate();
    },
  },
};
</script>

<style>
.age-calculator {
  font-family: Arial, sans-serif;
  text-align: center;
}
</style>

// react-calculator/react-calculator/src/App.js
import React, { useState } from 'react';

function App() {
  const [birthDate, setBirthDate] = useState('');
  const [age, setAge] = useState('');

  const handleInputChange = (event) => {
    setBirthDate(event.target.value);
  };

  const calculateAge = (birthDate) => {
    const today = new Date();
    const birthDateObj = new Date(birthDate);
    let age = today.getFullYear() - birthDateObj.getFullYear();
    const monthDiff = today.getMonth() - birthDateObj.getMonth();
    if (monthDiff < 0 || (monthDiff === 0 && today.getDate() < birthDateObj.getDate())) {
      age--;
    }
    const month = (today.getMonth() + 12 - birthDateObj.getMonth()) % 12;
    const dayDiff = today.getDate() - birthDateObj.getDate();
    const day = dayDiff < 0 ? daysInMonth(today.getMonth(), today.getFullYear()) - birthDateObj.getDate() + today.getDate() : dayDiff;
    const hour = today.getHours() - birthDateObj.getHours();
    const minute = today.getMinutes() - birthDateObj.getMinutes();
    const second = today.getSeconds() - birthDateObj.getSeconds();

    return {
      age: age,
      month: month,
      day: day,
      hour: hour,
      minute: minute,
      second: second
    };
  };

  const handleSubmit = (event) => {
    event.preventDefault();
    const ageObj = calculateAge(birthDate);
    setAge(ageObj);
  };

  const daysInMonth = (month, year) => {
    return new Date(year, month + 1, 0).getDate();
  };

  return (
    <div className="age-calculator">
      <h1>Age Calculator</h1>
      <form onSubmit={handleSubmit}>
        <label>
          Birthdate:
          <input type="date" value={birthDate} onChange={handleInputChange} />
        </label>
        <button type="submit">Calculate Age</button>
      </form>
      {age && (
        <div>
          <p>Your age is {age.age} years, {age.month} months, {age.day} days, {age.hour} hours, {age.minute} minutes, and {age.second} seconds old.</p>
        </div>
      )}
    </div>
  );
}

export default App;
